Game_Guide_App/Game_Guide_App/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('game_app.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Game_Guide_App/game_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.main, name='main'),
    path('all_games/', views.all_games, name='all_games'),
    path('all_guides/', views.all_guides, name='all_guides'),
    path('my_guides/', views.my_guides, name='my_guides'),
    path('my_guides/create/', views.create, name='create'),
    path('all_games/guides_by_category/<slug:slug>/', views.guides_by_cat, name='guides_by_cat'),
    path('all_games/guides_by_category/guide_description/<int:pk>', views.guide_desc, name='guide_desc'),
    path('sign_up/', views.sign_up, name='sign_up'),
    path('login/', views.login_view, name='login_view'),
    path('logout_action/', views.logout_action, name='logout_action'),
    path('sorry/', views.sorry, name='sorry'),
    path('my_guides/delete/<int:pk>/', views.delete_guide, name='delete_guide')
]

Game_Guide_App/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('game_app.urls'))
]

game_app/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.home_page, name='home_page'),
    path('allgames/', views.allgames_page, name='allgames_page'),
    path('allguides/', views.allguides_page, name='allguides_page'),
    path('myguides/', views.myguides_page, name='myguides_page'),
    path('post/detail/<int:pk>/', views.description_page, name='description_page'),
    path('allgames/category/<slug:slug>/', views.guides_by_category_page, name='guides_by_category_page'),
    path('myguides/create/', views.create_page, name='create_page'),
    path('registration/', views.sign_up_page, name='sign_up_page'),
    path('authorization/', views.login_page, name='login_page'),
    path('logout/', views.logout_action, name='logout_action'),
]

# Serve media files in development mode
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


Game_Guide_App/game_app/models.py
import os
from django.db import models
from datetime import datetime
from django.contrib.auth.models import User
from pytils.translit import slugify

class GameCategory(models.Model):
    gamename = models.CharField("Game name", max_length=100)
    gameimage = models.ImageField(upload_to='uploads/')
    slug = models.SlugField(unique=True, editable=False, blank=True)

    def __str__(self):
        return self.gamename
    
    def save(self, *args, **kwargs):
        self.slug = slugify(self.gamename)
        super().save(*args, **kwargs)

    def delete(self, *args, **kwargs):
        if self.gameimage:
            if os.path.isfile(self.gameimage.path):
                os.remove(self.gameimage.path)
        super().delete(*args, **kwargs)


class GuideDesc(models.Model):
    title = models.CharField(max_length=120, verbose_name="Title")
    date = models.DateField(default=datetime.now)
    image = models.ImageField(upload_to='images/', verbose_name="Image")
    description = models.TextField(verbose_name="Description")
    author = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="Author")
    category = models.ForeignKey(GameCategory, on_delete=models.CASCADE, verbose_name="category")

    def __str__(self):
        return self.title
    
    def delete(self, *args, **kwargs):
        if self.image:
            if os.path.isfile(self.image.path):
                os.remove(self.image.path)
                
        super().delete(*args, **kwargs)
    

game_app/models.py
from django.db import models
from pytils.translit import slugify
from datetime import datetime
from django import forms

class Category(models.Model):
    name = models.CharField("Название категории", max_length=255)
    slug = models.SlugField(unique=True, editable=False, blank=True)
    image = models.CharField("URL-фото", max_length=500)

    class Meta:
        verbose_name = "Категория"
        verbose_name_plural = "Категории"

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        super().save(*args, **kwargs)

class Guide(models.Model):
    title = models.CharField("Название гайда", max_length=255)
    image = models.CharField("URL-фото", max_length=500)
    creator = models.CharField("Автор", max_length=255)
    date = models.DateTimeField("Дата и время публикации", default=datetime.now)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='guides')
    description = models.TextField("Описание", blank=True)  # Add this line for the description

    class Meta:
        verbose_name = "Гайд"
        verbose_name_plural = "Гайды"

    def __str__(self):
        return f"{self.title} by {self.creator}"
    
class Game(models.Model):
    title = models.CharField("Название гайда", max_length=255)
    image = models.CharField("URL-фото", max_length=500)

    class Meta:
        verbose_name = "Игра"
        verbose_name_plural = "Игры"

    def __str__(self):
        return f"Game with image URL: {self.image}"

class RegistrationForm(forms.Form):
    username = forms.CharField(label='User', max_length=100)
    email = forms.EmailField(label='E-mail')
    password1 = forms.CharField(label='Pass1', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Pass2', widget=forms.PasswordInput)

class GamePost(models.Model):
    CATEGORY_CHOICES = [
        ('Minecraft', 'Minecraft'),
        ('Doom', 'Doom'),
        ('Terraria', 'Terraria'),
        ('Stardew Valley', 'Stardew Valley'),
    ]

    title = models.CharField(max_length=100)
    category = models.CharField(max_length=50, choices=CATEGORY_CHOICES)
    image = models.ImageField(upload_to='uploads/')
    description = models.TextField()

    def __str__(self):
        return self.title

Game_Guide_App/game_app/forms.py
from django import forms
from .models import GuideDesc
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class CreateForm(forms.ModelForm):
     def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['category'].empty_label = "Category"

     class Meta:    
          model = GuideDesc
          fields = ['title', 'category', 'image', 'description']
          widgets = {
               'title': forms.TextInput(attrs={'class':'create_input', 'placeholder':'Title'}),
               'category': forms.Select(attrs={'class':'create_category'}),
               'description': forms.Textarea(attrs={'class':'create_description', 'placeholder':'Description...', 'rows':4}) 
          }



class UserForm(UserCreationForm):
     class Meta:
          model = User
          fields = ["username", "email", "password1", "password2"]
          widgets = {
               'username': forms.TextInput(attrs={'placeholder': 'Username'}),
               'email': forms.EmailInput(attrs={'placeholder': 'E-mail'})
          }

game_app/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import GamePost

class NewUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ["username", "email", "password1", "password2"]

class GamePostForm(forms.ModelForm):
    class Meta:
        model = GamePost
        fields = ['title', 'category', 'image', 'description']

Game_Guide_App/game_app/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import *
from .forms import *
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.decorators import login_required

def main(request):
    guides = GuideDesc.objects.all().order_by('-date')[:3]
    context = {
        'guides' : guides
    }
    return render(request, "./main.html", context)


def all_games(request):
    categories = GameCategory.objects.all()
    context = {
        'categories' : categories
    }
    return render(request, "./allgames.html", context)


def all_guides(request):
    guides = GuideDesc.objects.all().order_by('-date')
    context = {
        'guides' : guides
    }
    return render(request, "./allguides.html", context)


def guides_by_cat(request, slug):
    gamecategory = get_object_or_404(GameCategory, slug=slug)
    guidedesc = GuideDesc.objects.filter(category=gamecategory)
    context = {
        'gamecategory' : gamecategory,
        'guidedesc' : guidedesc
    }

    return render(request, "./guidesbycat.html", context)


def guide_desc(request, pk):
    guide_description = get_object_or_404(GuideDesc, pk=pk)
    context = {
        'guide_description' : guide_description
    }

    return render(request, "./guidedesc.html", context)


@login_required
def my_guides(request):
    guides = GuideDesc.objects.filter(author=request.user).order_by('-date')
    context = {
        'guides' : guides
    }
    return render(request, "./myguides.html", context)


@login_required
def create(request):
    if request.method == "POST":
        form = CreateForm(request.POST, request.FILES)
        if form.is_valid():
            guide = form.save(commit=False)
            guide.author = request.user
            guide.save()
            return redirect('my_guides')
    
    else:
        form = CreateForm()

    return render(request, './create.html', {'form':form})


@login_required
def delete_guide(request, pk):
    guide = get_object_or_404(GuideDesc, pk=pk)
    if request.method == "POST":
        if guide.author == request.user:
            guide.delete()
            return redirect('my_guides')


def sign_up(request):   
    if request.method == "POST":
        form = UserForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('main')
    else:
        form = UserForm()

    return render(request, './signup.html', {'form':form})


def login_view(request):
    if request.method == "POST":
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('main') 
    else:
        form = AuthenticationForm()

    return render(request, "./login.html", {'form':form})


def logout_action(request):
    logout(request)
    return redirect('main')


def sorry(request):
    return render(request, "./sorry.html")

game_app/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Category, Guide
from django.contrib.auth import login, authenticate, logout
from .forms import NewUserForm, GamePostForm
from django.contrib.auth.forms import AuthenticationForm

def home_page(request):
    categories = Category.objects.all()
    guides = Guide.objects.all()
    context = {
        'categories': categories,
        'guides': guides,
    }
    return render(request, "./home.html", context)

def description_page(request, pk):
    guide = get_object_or_404(Guide, pk=pk)
    context = {
        'guide': guide
    }
    return render(request, "./description.html", context)

def allguides_page(request):
    categories = Category.objects.all()
    guides = Guide.objects.all()
    context = {
        'categories': categories,
        'guides': guides,
    }
    return render(request, "./allguides.html", context)

def myguides_page(request):
    categories = Category.objects.all()
    guides = Guide.objects.all()
    context = {
        'categories': categories,
        'guides': guides,
    }
    return render(request, "./myguides.html", context)

def allgames_page(request):
    categories = Category.objects.all()
    guides = Guide.objects.all()
    context = {
        'categories': categories,
        'guides': guides,
    }
    return render(request, "./allgames.html", context)

def guides_by_category_page(request, slug):
    category = get_object_or_404(Category, slug=slug)
    guides = Guide.objects.filter(category=category)
    context = {
        'category': category,
        'guides': guides,
    }
    return render(request, "./guide_by_category.html", context)

def create_page(request):
    if request.method == 'POST':
        form = GamePostForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('home')  # Redirect to a page after submission, e.g., home
    else:
        form = GamePostForm()
    return render(request, 'create.html', {'form': form})

def sign_up_page(request):
    if request.method == "POST":
        form = NewUserForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('home_page')
    else:
        form = NewUserForm()
    context = {
        'form': form
    }
    return render(request, "./registration.html", context)

def login_page(request):
    if request.method == "POST":
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('home_page')
    else:
        form = AuthenticationForm()

    context = {
        'form': form
    }
    return render(request, "./authorization.html", context)

def logout_action(request):
    logout(request)
    return redirect('home_page')

Game_Guide_App/game_app/templates/allgames.html
{% extends 'base.html' %}

{% block title %}All Games{% endblock %}

{% block content %}
    <section class="mobile_block">
        <div class="second_header">
            <span class="txt">All Games</span>
        </div>
        <div class="container">
            <div class="category_list">
                {% for category in categories %}
                    <a href="{% url 'guides_by_cat' slug=category.slug %}">
                        <div class="category_item">
                            <img src="{{category.gameimage.url}}" alt="{{category.title}}" class="game_image">
                        </div>
                    </a>
                {% endfor %}
            </div>
        </div>
    </section>
{% endblock %}

Game_Guide_App/game_app/templates/allguides.html
{% extends 'base.html' %}

{% block title %}All Guides{% endblock %}

{% block content %}
<section class="mobile_block">
    <div class="second_header">
        <span class="txt">All Guides</span>
    </div>

    {% for guide in guides%}
    <div class="container">
        <div class="defined_game_list">
            <a href="{% url 'guide_desc' pk=guide.pk %}">
                <div class="basebal">
                    <div class="create_head">
                        <span class="title">{{guide.title}}</span>      
                    </div>
                    <div class="create_main">
                        <img src={{guide.image.url}} alt="card_image" class="card_image">
                        <span class="card_txt">Creator : {{guide.author.username}}</span>
                        <span class="card_txt">Category : {{guide.category}}</span>
                        <span class="card_txt">Date : {{guide.date|date:"d.m.Y"}}</span>
                    </div>
                </div>
            </a>
        </div>
    </div>
    {% endfor %}
</section>
{% endblock %}

Game_Guide_App/game_app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static './CSS/stylecss.css' %}">
</head>

<body>
    {% block header %}
    <header class="header">
        <div class="container">
            <button class="header_button" onclick="ShowMenu();">
                <img src="{% static 'assets/icons/Games.svg' %}" alt="">
            </button>
        </div>
    </header>
    <audio id="get-out" src="{% static './sounds/getout.mp3' %}" preload="auto"></audio>
    <div id="overlay" style="display: none;"  onclick="ShowMenu()">
        <div class="menu" onclick="event.stopPropagation()">
            {% if user.is_authenticated %}
            <div class="menu_header">
                <img src="{% static './assets/icons/Icon.svg' %}" alt="">
                <span class="menu_title">{{user.username}}</span>
            </div>
            {% else %}
            <div class="menu_header">
                <img src="{% static './assets/icons/Icon.svg' %}" alt="">
                <span class="menu_title">No Username</span>
            </div>
            {% endif %}
            <div class="menu_main">
                <a href="{% url 'main' %}" class="">
                    <button class="menu_button">
                        Main
                    </button>
                </a>
                <a href="{% url 'all_games' %}" class="">
                    <button class="menu_button">
                        All Games 
                    </button>
                </a>
                <a href="{% url 'all_guides' %}" class="">
                    <button class="menu_button">
                        All Guides 
                    </button>
                </a>
                {% if user.is_authenticated %}
                <a href="{% url 'my_guides' %}" class="">
                   <button class="menu_button">
                        My Guides
                    </button>
                </a>
                {% else %}
                <a href="{% url 'sorry' %}" class="">
                   <button class="menu_button">
                        My Guides
                    </button>
                </a>
                {% endif %}
                {% if not user.is_authenticated %}
                <a href="{% url 'sign_up' %}" class="">
                   <button class="menu_button">
                        Sign Up
                    </button>
                </a>
                <a href="{% url 'login_view' %}" class="">
                   <button class="menu_button">
                        Login
                    </button>
                </a>
                {% else %}
                <a href="{% url 'logout_action' %}" class="">
                    <button class="menu_button" onclick="PlaySound();">
                        Exit: {{user.email}}
                    </button>
                </a>
                {% endif %} 
            </div>
        </div>
    </div>
    {% endblock %}
    
    <main>
        {% block content %}
        
        {% endblock %}
    </main>
    <script src="{% static './Js/script.js' %}"></script>
</body>
</html>         

Game_Guide_App/game_app/templates/create.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Create{% endblock %}


{% block header %}
<header class="header">
    <div class="container">
        <a href="{% url 'my_guides' %}">
            <button class="header_button" onclick="ShowMenu();">
                <img src="{% static 'assets/icons/BackIcon.svg' %}" alt="Back Icon">
            </button>
        </a>
    </div>
</header>
{% endblock %}


{% block content %}
<section class="mobile_block">
    <div class="second_header">
        <span class="txt">Create</span>
    </div>

    <form action="{% url 'create' %}" class="form-create" method="post" enctype="multipart/form-data">
        {% csrf_token %}

        <div class="container">
            <div class="create_block is-light_yellow">
                {{form.title}}
                {{form.category}}
                <label for="id_image" class="create_upload" style="display: flex;">
                    <img src="{% static './assets/icons/plus.svg' %}" alt="plus">
                    Upload image
                    {{form.image}}  
                </label>
                {{form.description}}
                <div class="submit_block">
                    <button type="submit" class="submit_btn">Submit</button>
                </div>
            </div>
        </div>

    </form>
</section>
{% endblock %}

Game_Guide_App/game_app/templates/guidedesc.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Description{% endblock %}


{% block header %}
<header class="header">
    <div class="container">
        <a href="{% url 'all_games' %}">
            <button class="header_button" onclick="ShowMenu();">
                <img src="{% static 'assets/icons/BackIcon.svg' %}" alt="Back Icon">
            </button>
        </a>
    </div>
</header>
{% endblock %}


{% block content %}
<section class="mobile_block">
    <div class="second_header">
        <span class="txt">Description</span>
    </div>

    <div class="container">
        <div class="create_block is-light_yellow">
            <div class="description_box">
                <h1 class="desc_title">{{guide_description.title}}</h1>
                <strong><span class="desc_date">DATE : {{guide_description.date|date:"d.m.Y"}}</span></strong>
                <img src={{guide_description.image.url}} alt="desc_image" class="desc_image">
                <p class="description">{{guide_description.description|linebreaksbr}}</p>
            </div>
        </div>
        <div class="create_block is-light_yellow">
            <div class="description_box">
                <div class="author">Author : {{guide_description.author.username}}</div>
                <div class="game_category">Category : {{guide_description.category}}</div>
            </div>
        </div>
    </div>
    
</section>
{% endblock %}

Game_Guide_App/game_app/templates/guidesbycat.html
{% extends 'base.html' %}

{% block title %}{{ gamecategory.gamename }}{% endblock %}

{% block content %}
<section class="mobile_block">
    <div class="second_header">
        <span class="txt">{{ gamecategory.gamename }}</span>
    </div>

    {% for guide in guidedesc %}
    <div class="container">
        <div class="defined_game_list">
            <a href="{% url 'guide_desc' pk=guide.pk %}">
                <div class="basebal">
                    <div class="create_head">
                        <span class="title">{{guide.title}}</span>      
                    </div>
                    <div class="create_main">
                        <img src={{guide.image.url}} alt="card_image" class="card_image">
                        <span class="card_txt">Creator : {{guide.author.username}}</span>
                        <span class="card_txt">Category : {{guide.category}}</span>
                        <span class="card_txt">Date : {{guide.date|date:"d.m.Y"}}</span>
                    </div>
                </div>
            </a>
        </div>
    </div>
    {% endfor %}
</section>
{% endblock %}

Game_Guide_App/game_app/templates/login.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Login{% endblock %}

{% block header %}{% endblock %}

{% block content %}
<form method="post" class="form">
    {% csrf_token %}
    <div class="main_block">
        <span class="image_block"><img src="{% static './assets/icons/Icon.svg' %}" alt="icon" class="icon"></span>
        <div class="registration">Authorization</div>
        

        <div class="input_block">
            <label for="id_username">Username</label>
            <span class="email_block_bd">
                {{form.username}}
            </span>
        </div>
        <div class="error">{{ form.username.errors }}</div>
        
        <div class="input_block">
            <label for="id_password">Password</label>
            <span class="email_block_bd">
                {{form.password}}
            </span>
        </div>  
        <div class="error">{{ form.non_field_errors }}</div>

        <div class="buttons">
            <button type="submit" class="main_btn">Login</button>
            <a href="{% url 'sign_up' %}">
                <button type="button" class="second_btn">Create a new account?</button>
            </a>
        </div>
    </div>
</form>
{% endblock %}

Game_Guide_App/game_app/templates/main.html
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
<section class="mobile_block">
    <div class="second_header">
        <span class="txt">Home</span>
    </div>

    <div class="logo">
        <span class="logo_txt">GAME</span>
        <span class="logo_txt is-green_txt">HUB</span>
    </div>
    <div class="forflex">
        <div class="line"></div>
    </div>

    {% for guide in guides%}
    <div class="container">
        <div class="defined_game_list">
            <a href="{% url 'guide_desc' pk=guide.pk %}">
                <div class="basebal">
                    <div class="create_head">
                        <span class="title">{{guide.title}}</span>      
                    </div>
                    <div class="create_main">
                        <img src={{guide.image.url}} alt="card_image" class="card_image">
                        <span class="card_txt">Creator :  {{guide.author.username}}</span>
                        <span class="card_txt">Category : {{guide.category}}</span>
                        <span class="card_txt">Date : {{guide.date|date:"d.m.Y"}}</span>
                    </div>
                </div>
            </a>
        </div>
    </div>
    {% endfor %}
    
</section>
{% endblock %}

Game_Guide_App/game_app/templates/myguides.html
{% extends 'base.html' %}
{% load static %}

{% block title %}All Games{% endblock %}


{% block content %}
<form id="deleteform" method="post" action="">
    {% csrf_token %}
    <div id="overlay2" style="display: none;" onclick="ShowDelete();">
        <div  class="yousure" onclick="event.stopPropagation()">
            <span class="delete_title">Are you sure about that?</span>
            <div class="delete_buttons">
                <button type="submit" class="btn is-green">
                    Yes
                </button>
                
                <button type="button" class="btn is-red" onclick="ShowDelete();">
                    No
                </button>
            </div>
        </div>
    </div>
</form>

<section class="mobile_block">
    <div class="second_header">
        <span class="txt">My Guides</span>
    </div>
   
    <div class="container">
        <div class="create_block">
            <a href="{% url 'create' %}">
                <div class="creation">
                    <div><img src="{% static './assets/icons/Editors.svg' %}" alt=""></div>
                    <span class="create">Create</span>
                </div>
            </a>

            {% for guide in guides%}
                <a href="{% url 'guide_desc' pk=guide.pk %}">
                    <div class="basebal">
                        <div class="create_head">
                            <span class="title">{{guide.title}}</span> 
                            <div class="images" onclick="event.preventDefault();">
                                <button class="edit_trash_btn" onclick="ShowDelete('{{guide.pk}}');"><img src="{% static './assets/icons/Delete.svg' %}" alt="delete_button"></button>
                            </div>      
                            </div>
                        <div class="create_main">
                            <img src={{guide.image.url}} alt="card_image" class="card_image">
                            <span class="card_txt">Creator : {{guide.author.username}}</span>
                            <span class="card_txt">Category : {{guide.category}}</span>
                            <span class="card_txt">Date : {{guide.date|date:"d.m.Y"}}</span>
                        </div>
                    </div>
                </a>
            {% endfor %}
        </div>
    </div>
</section>

{% endblock %}

Game_Guide_App/game_app/templates/signup.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Sign up{% endblock %}

{% block header %}{% endblock %}

{% block content %}
<form method="post" class="form">
    {% csrf_token %}
    <div class="main_block">
        <span class="image_block"><img src="{% static './assets/icons/Icon.svg' %}" alt="icon" class="icon"></span>
        <div class="registration">Registration</div>
        
        <div class="input_block">
            <label for="id_username">Username</label>
            <span class="email_block_bd">
                {{form.username}}
            </span>
        </div>
        <div class="error">{{form.username.errors}}</div>
        <div class="input_block">
            <label for="id_email">E-mail</label>
            <span class="email_block_bd">
                {{form.email}}
            </span>
        </div>
        <div class="error">{{form.email.errors}}</div>
        <div class="input_block">
            <label for="id_password1">Password 1</label>
            <span class="email_block_bd">
                {{form.password1}}
            </span>
        </div>
        <div class="error">{{form.password1.errors}}</div>
        <div class="input_block">
            <label for="id_password2">Password 2</label>
            <span class="email_block_bd">
                {{form.password2}}
            </span>
        </div>
        <div class="error">{{form.password2.errors}}</div>

        <div class="buttons">
            <button type="submit" class="main_btn">Sign up</button>
            <a href="{% url 'login_view' %}">
                <button type="button" class="second_btn">Already have an account?</button>
            </a>
        </div>
    </div>
</form>
{% endblock %}

Game_Guide_App/game_app/templates/sorry.html
{% extends 'base.html' %}

{% block title %}All Games{% endblock %}

{% block content %}
    <section class="sorry_block">
        <div class="sorry_yellow">
            <div class="green_back">
                <h1>To access this catalog you need to be signed up or logged in, sorry :/</h1>
            </div>
            <div class="btns">
                <a href="{% url 'sign_up' %}">
                    <button>Sign Up</button>
                </a>
                <a href="{% url 'login_view' %}">
                    <button>Login</button>
                </a>
            </div>
        </div>
    </section>
{% endblock %}